GET http://localhost:3000/actors


###
GET http://localhost:3000/actors/5


###
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Benedict",
   "last_name": "Cumberbatch",
    "known_for": "Sherlock"
}

###
PATCH http://localhost:3000/actors/5.json
Content-Type: application/json

{
  "first_name": "Benedict!!!"
   
}


###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/3

###
POST http://localhost:3000/movies/2.json
Content-Type: application/json

{
  "title": "Taken",
   "year": 2008,
    "plot": "Bryan Mills (Liam Neeson), a former government operative, is trying to reconnect with his daughter, Kim (Maggie Grace)",
    "director": "Pierre Morel",
    "english": true
}

###
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{
  "director": "James Cameron"
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}