GET http://localhost:3000/actors


###
GET http://localhost:3000/actors/5



###
POST http://localhost:3000/actors.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjE4MDY4NjB9.yLUDZn2Bdz5dmmVqIDqsmEH71X2FD-aGwK8hvWT2Reg
Content-Type: application/json

{
  "first_name": "Liam",
   "last_name": "Neeson",
    "known_for": "movie",
    "movie_id": 4,
    "age": 65,
    "gender": "male"
}

###
PATCH http://localhost:3000/actors/5.json
Content-Type: application/json

{
  "first_name": "Benedict!!!"
   
}


###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/3

###
POST http://localhost:3000/movies.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjE4MDY4NjB9.yLUDZn2Bdz5dmmVqIDqsmEH71X2FD-aGwK8hvWT2Reg

{
  "title": "Taken",
   "year": 2008,
    "plot": "Bryan Mills (Liam Neeson), a former government operative, is trying to reconnect with his daughter, Kim (Maggie Grace)",
    "director": "Pierre Morel",
    "english": true
}

###
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{
  "director": "James Cameron"
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "BEN",
  "email": "ben@ben.com",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@ben.com",
  "password": "password"
}